apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "kestra.fullname" . }}-config
  labels:
    {{- include "kestra.labels" . | nindent 4 }}
data:
{{- if .Values.configurations.application }}
  application.yml: |
{{ .Values.configurations.application | toYaml | indent 4}}
{{- end }}
