{{- $global := .Values }}
{{- range $name, $config := $global.deployments }}
{{- if $config.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ include "kestra.fullname" $ }}-{{ $name }}"
  labels:
    {{- include "kestra.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $name }}
    {{- with $global.common.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with $config.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with $global.common.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with $config.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ ternary $config.replicas $global.common.replicas (hasKey $config "replicas") }}
  selector:
    matchLabels:
      {{- include "kestra.selectorLabels" $ | nindent 6 }}
      app.kubernetes.io/component: {{ $name }}
  strategy:
    {{- toYaml (ternary $config.strategy $global.common.strategy (hasKey $config "strategy")) | nindent 4 }}
  template:
    metadata:
      labels:
        {{- include "kestra.selectorLabels" $ | nindent 8 }}
        app.kubernetes.io/component: {{ $name }}
        {{- with $global.common.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with $config.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        {{- with $global.common.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with $config.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "kestra.serviceAccountName" $ }}
      {{- $imagePullSecrets := ternary $config.imagePullSecrets $global.common.imagePullSecrets (hasKey $config "imagePullSecrets") }}
      {{- if $imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml $imagePullSecrets | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: {{ ternary $config.terminationGracePeriodSeconds $global.common.terminationGracePeriodSeconds (hasKey $config "terminationGracePeriodSeconds") }}
      {{- $podSecurityContext := ternary $config.podSecurityContext $global.common.podSecurityContext (hasKey $config "podSecurityContext") }}
      {{- if $podSecurityContext }}
      securityContext:
        {{- toYaml $podSecurityContext | nindent 8 }}
      {{- end }}
      {{- $nodeSelector := ternary $config.nodeSelector $global.common.nodeSelector (hasKey $config "nodeSelector") }}
      {{- if $nodeSelector }}
      nodeSelector:
        {{- toYaml $nodeSelector | nindent 8 }}
      {{- end }}
      {{- $affinity := ternary $config.affinity $global.common.affinity (hasKey $config "affinity") }}
      {{- if $affinity }}
      affinity:
        {{- toYaml $affinity | nindent 8 }}
      {{- end }}
      {{- $tolerations := ternary $config.tolerations $global.common.tolerations (hasKey $config "tolerations") }}
      {{- if $tolerations }}
      tolerations:
        {{- toYaml $tolerations | nindent 8 }}
      {{- end }}
      volumes:
        - name: {{ template "kestra.fullname" $ }}-config
          configMap:
            name: {{ template "kestra.fullname" $ }}-config
            items:
              - key: application.yml
                path: application.yml
        {{- range $global.configurations.configmaps }}
        - name: {{ .name }}
          configMap:
            name: {{ .name }}
            items:
              - key: {{ .key }}
                path: {{ .key }}
        {{- end }}
        {{- range $global.configurations.secrets }}
        - name: {{ .name }}
          secret:
            secretName: {{ .name }}
            items:
              - key: {{ .key }}
                path: {{ .key }}
        {{- end }}
        {{- $volumes := ternary $config.extraVolumes $global.common.extraVolumes (hasKey $config "extraVolumes") }}
        {{- if $volumes }}
          {{- toYaml $volumes | nindent 8 }}
        {{- end }}
      {{- $initContainers := ternary $config.initContainers $global.common.initContainers (hasKey $config "initContainers") }}
      {{- if $initContainers }}
      initContainers:
        {{- toYaml $initContainers | nindent 8 }}
      {{- end }}
      containers:
        - name: kestra-{{ $name }}
          image: "{{ $global.image.repository }}:{{ default $.Chart.AppVersion $global.image.tag }}"
          imagePullPolicy: {{ $global.image.pullPolicy }}
          command:
            - "sh"
            - "-c"
            - | 
                exec /app/kestra server {{ $name }} \
                {{- if eq $name "standalone" -}}
                --worker-thread={{ $config.workerThreads }}
                {{- end -}}
          {{- $resources := ternary $config.resources $global.common.resources (hasKey $config "resources") }}
          {{- if $resources }}
          resources:
            {{- toYaml $resources | nindent 12 }}
          {{- end }}
          env:
            - name: MICRONAUT_CONFIG_FILES
              value: |
                /app/application.yml,
                {{- range $global.configurations.configmaps }}
                /app/{{ .key }},
                {{- end }}
                {{- range $global.configurations.secrets }}
                /app/{{ .key }},
                {{- end }}
          {{- $env := ternary $config.extraEnv $global.common.extraEnv (hasKey $config "extraEnv") }}
          {{- if $env }}
            {{- toYaml $env | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: {{ template "kestra.fullname" $ }}-config
              mountPath: /app/application.yml
              subPath: application.yml
            {{- range $global.configurations.configmaps }}
            - name: {{ .name }}
              mountPath: /app/{{ .key }}
              subPath: {{ .key }}
            {{- end }}
            {{- range $global.configurations.secrets }}
            - name: {{ .name }}
              mountPath: /app/{{ .key }}
              subPath: {{ .key }}
            {{- end }}
            {{- $volumeMounts := ternary $config.extraVolumeMounts $global.common.extraVolumeMounts (hasKey $config "extraVolumeMounts") }}
            {{- if $volumeMounts }}
              {{- toYaml $volumeMounts | nindent 12 }}
            {{- end }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: management
              containerPort: 8081
              protocol: TCP
          {{- $securityContext := ternary $config.securityContext $global.common.securityContext (hasKey $config "securityContext") }}
          {{- if $securityContext }}
          securityContext:
            {{- toYaml $securityContext | nindent 12 }}
          {{- end }}
          {{- $startupProbe := ternary $config.startupProbe $global.common.startupProbe (hasKey $config "startupProbe") }}
          {{- if $startupProbe }}
          startupProbe:
            {{- toYaml $startupProbe | nindent 12 }}
          {{- end }}
          {{- $livenessProbe := ternary $config.livenessProbe $global.common.livenessProbe (hasKey $config "livenessProbe") }}
          {{- if $livenessProbe }}
          livenessProbe:
            {{- toYaml $livenessProbe | nindent 12 }}
          {{- end }}
          {{- $readinessProbe := ternary $config.readinessProbe $global.common.readinessProbe (hasKey $config "readinessProbe") }}
          {{- if $readinessProbe }}
          readinessProbe:
            {{- toYaml $readinessProbe | nindent 12 }}
          {{- end }}
        {{- $extraContainers := ternary $config.extraContainers $global.common.extraContainers (hasKey $config "extraContainers") }}
        {{- range $extraContainers }}
        - {{- toYaml . | nindent 10 }}
        {{- end }}
{{- end }}
{{- end }}
